FROM ubuntu:22.04
ENV REFRESHED_AT 2022-12-19

LABEL maintainer="Matthieu Boileau <matthieu.boileau@math.unistra.fr>"

ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing && \
    apt-get install -y \ 
    make \
    texlive-xetex \
    texlive-fonts-extra \
    texlive-science \
    python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb /tmp/
RUN dpkg -i /tmp/pandoc-2.19.2-1-amd64.deb

RUN useradd -m -s /bin/bash euler
ENV HOME /home/euler
RUN chown -R euler:euler /home/euler
USER euler
WORKDIR $HOME
RUN pip install --user pantable
ENV PATH $HOME/.local/bin:$PATH

CMD /bin/bash
